version: '1.0'
name: develop-line
displayName: develop分支流水线
triggers:
  trigger: auto
  push:
    branches:
      include:
        - develop
stages:
  - name: stage-cc3a53a4
    displayName: 编译
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - npm install && rm -rf ./dist && npm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
permissions:
  - role: admin
    members: []
